support for feature reports on HID interace
qzind/tray pull request #733
Opened 2020-11-23 19:53 UTC by koltenpearson

should fix #363 and add support for HID feature reports

this has been tested briefly on linux, still needs to be tested on windows and mac

this only adds functionality to the HID interface, it does not at it to the USB one

2020-12-08 06:12 UTC, bberenz requested changes

2020-12-09 16:43 UTC, koltenpearson commented on src/qz/communication/PJHA_HidIO.java
> +        //once the dependency is updated, the new version accepts the report id separately from the data
looks like you updated it to version 0.0.3, but their github repo shows up to 0.0.10, with the deprecation currently on master and not yet tagged
https://github.com/nyholku/purejavahidapi

so I guess not

2020-12-09 17:05 UTC, bberenz commented on src/qz/communication/PJHA_HidIO.java
> +        //once the dependency is updated, the new version accepts the report id separately from the data
oh, you know what, it looks like they never updated their [pom.xml](https://github.com/nyholku/purejavahidapi/blob/master/pom.xml#L7) versioning
we should have the latest on their master though, as it was built from source

2020-12-09 17:06 UTC, tresf commented on src/qz/communication/PJHA_HidIO.java
> +        //once the dependency is updated, the new version accepts the report id separately from the data
Good catch @bberenz.  Can you patch this on our `master` branch so we aren't confused down the road?

2020-12-09 17:09 UTC, tresf commented on src/qz/communication/PJHA_HidIO.java
> +        //once the dependency is updated, the new version accepts the report id separately from the data
FYI, also requested the change upstream: https://github.com/nyholku/purejavahidapi/pull/77

2020-12-09 17:33 UTC, koltenpearson commented on src/qz/communication/PJHA_HidIO.java
> +        //once the dependency is updated, the new version accepts the report id separately from the data
made the adjustments to the method, and it compiles successfully

2020-12-14 18:23 UTC, bberenz approved these changes

2020-12-14 21:44 UTC, merged